import React from 'react'
import Hero from '../../components/AboutComponents/Hero'
import Mission from '../../components/AboutComponents/Mission'
import Choose from '../../components/AboutComponents/Choose'
import Plan from '../../components/AboutComponents/Plan'
import Head from 'next/head'

const About = () => {
  return (
    
    <>
    <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Hero/>
    <Mission/>
    <Choose/>
    <Plan/>
    </>
  )
}

export default About